name: Sync with RA

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  detect-changes:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1.51.3
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: bundle install
    - name: Run cron_job
      run: bundle exec rake cron_job
